package me.ohvalsgod.guardsplus.command;

import com.besaba.revonline.pastebinapi.impl.paste.PasteBuilderImpl;
import com.besaba.revonline.pastebinapi.paste.Paste;
import com.besaba.revonline.pastebinapi.paste.PasteExpire;
import com.besaba.revonline.pastebinapi.paste.PasteVisiblity;
import com.besaba.revonline.pastebinapi.response.Response;
import me.ohvalsgod.guardsplus.GuardsPlus;
import me.ohvalsgod.guardsplus.util.InventoryUtils;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;

public class TemporaryItemstackSerializerCommand implements CommandExecutor {

    public boolean onCommand(CommandSender commandSender, Command command, String s, String[] strings) {

        if (!(commandSender instanceof Player)) {
            commandSender.sendMessage("This command is only available to players.");
            return false;
        }

        return pasteInventory((Player) commandSender);
    }

    public static boolean pasteInventory(Player player) {
        if (isInventoryEmpty(player)) {
            player.sendMessage("Your inventory is empty, but the pastebin will still be uploaded.");
        }

        String pasteFormat = "inventory: \"%s\"\narmor: \"%s\"";
        String pasteRawContents = String.format(pasteFormat, InventoryUtils.itemStackArrayToBase64(player.getInventory().getContents()), InventoryUtils.itemStackArrayToBase64(player.getInventory().getArmorContents()));

        Paste paste = new PasteBuilderImpl()
                .setTitle("Serialized inventory contents generated by " + player.getName())
                .setRaw(pasteRawContents)
                .setMachineFriendlyLanguage("text")
                .setVisiblity(PasteVisiblity.Unlisted)
                .setExpire(PasteExpire.OneHour)
                .build();

        Response<String> response = GuardsPlus.getInstance().getPastebinAPI().post(paste);

        if (response.hasError()) {
            player.sendMessage("There was an error posting your pastebin: " + response.getError());
            return false;
        }
        player.sendMessage("Your pastebin link has been posted, you can grab the contents from: " + response.get());
        player.sendMessage("This will expire in one hour.");
        return true;
    }

    private static boolean isInventoryEmpty(Player player) {
        int emptySlots = 0;

        for (int i = 0; i < player.getInventory().getContents().length; i++) {
            if (player.getInventory().getContents()[i] == null) {
                emptySlots++;
            }
        }

        for (int i = 0; i < player.getInventory().getArmorContents().length; i++) {
            if (player.getInventory().getContents()[i] == null) {
                emptySlots++;
            }
        }

        return emptySlots == 40;
    }

}
