package me.ohvalsgod.guardsplus.command;

import com.besaba.revonline.pastebinapi.impl.paste.PasteBuilderImpl;
import com.besaba.revonline.pastebinapi.paste.Paste;
import com.besaba.revonline.pastebinapi.paste.PasteVisiblity;
import com.besaba.revonline.pastebinapi.response.Response;
import me.ohvalsgod.guardsplus.GuardsPlus;
import me.ohvalsgod.guardsplus.util.InventoryUtils;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;

public class TemporaryItemstackSerializerCommand implements CommandExecutor {

    public boolean onCommand(CommandSender commandSender, Command command, String s, String[] strings) {

        if (!(commandSender instanceof Player)) {
            commandSender.sendMessage("This command is only available to players.");
            return false;
        }

        Player player = (Player) commandSender;

        if (command.getLabel().equalsIgnoreCase("debugserialize")) {
            if (isInventoryEmpty(player)) {
                player.sendMessage("Your inventory is empty, but the pastebin will still be uploaded.");
            }

            String pasteFormat = "inventory: \"%s\"\narmor: \"%s\"";
            String pasteRawContents = String.format(pasteFormat, InventoryUtils.itemStackArrayToBase64(player.getInventory().getContents()), InventoryUtils.itemStackArrayToBase64(player.getInventory().getArmorContents()));

            Paste paste = new PasteBuilderImpl()
                    .setTitle("Serialized inventory contents generated by " + player.getName())
                    .setVisiblity(PasteVisiblity.Unlisted)
                    .setRaw(pasteRawContents)
                    .build();

            Response<String> response = GuardsPlus.getInstance().getPastebinAPI().post(paste);

            if (response.hasError()) {
                player.sendMessage("There was an error posting your pastebin: " + response.getError());
                return false;
            }
            player.sendMessage("Your pastebin link has been posted, you can grab the contents from: " + response.get());
            return true;
        }

        return false;
    }

    private boolean isInventoryEmpty(Player player) {
        int emptySlots = 0;

        for (int i = 0; i < player.getInventory().getContents().length; i++) {
            if (player.getInventory().getContents()[i] == null) {
                emptySlots++;
            }
        }

        for (int i = 0; i < player.getInventory().getArmorContents().length; i++) {
            if (player.getInventory().getContents()[i] == null) {
                emptySlots++;
            }
        }

        return emptySlots == 40;
    }

}
